apply plugin: 'com.android.library'

android {
    compileSdkVersion 35
    ndkVersion "29.0.13113456"

    defaultConfig {
        namespace "com.theeasiestway.opus"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
        }

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }
}

tasks.register('copyReleaseLibsToEasyOpus', Copy) {
    def outputDir = "../easyopus/src/main/cpp/libs"
    from(fileTree(dir: "build/intermediates/cxx/Release", include: "**/obj/local/**/*.so")) {
        eachFile { file ->
            def idx = file.relativePath.segments.findIndexOf { it == 'local' }
            if (idx >= 0 && file.relativePath.segments.size() > idx + 1) {
                def newSegments = file.relativePath.segments[(idx + 1)..-1]
                file.relativePath = new RelativePath(true, *newSegments)
            }
        }
        includeEmptyDirs = false
    }
    into(outputDir)
    dependsOn 'externalNativeBuildRelease'
}
